"""Install the Chrome native messaging host and its launcher scripts.

Chrome derives an unpacked extension's ID from the public key embedded in
its manifest, so the ID is stable across machines and reinstalls. The native
host manifest restricts `allowed_origins` to exactly that ID, which is what
stops any other extension from talking to your vault.
"""

from __future__ import annotations

import base64
import hashlib
import json
import os
import stat
import sys
from pathlib import Path

from . import ui
from .vault import ensure_home, home

HOST_NAME = "com.tvault.host"

# Where each Chromium-family browser looks for native host manifests.
_MAC_ROOT = Path.home() / "Library" / "Application Support"
_LINUX_ROOT = Path.home() / ".config"

BROWSERS_MAC = {
    "chrome": _MAC_ROOT / "Google/Chrome",
    "chrome-beta": _MAC_ROOT / "Google/Chrome Beta",
    "chrome-canary": _MAC_ROOT / "Google/Chrome Canary",
    "chromium": _MAC_ROOT / "Chromium",
    "edge": _MAC_ROOT / "Microsoft Edge",
    "brave": _MAC_ROOT / "BraveSoftware/Brave-Browser",
    "vivaldi": _MAC_ROOT / "Vivaldi",
    "arc": _MAC_ROOT / "Arc/User Data",
}

BROWSERS_LINUX = {
    "chrome": _LINUX_ROOT / "google-chrome",
    "chrome-beta": _LINUX_ROOT / "google-chrome-beta",
    "chromium": _LINUX_ROOT / "chromium",
    "edge": _LINUX_ROOT / "microsoft-edge",
    "brave": _LINUX_ROOT / "BraveSoftware/Brave-Browser",
    "vivaldi": _LINUX_ROOT / "vivaldi",
}


def project_root() -> Path:
    return Path(__file__).resolve().parent.parent


def extension_dir() -> Path:
    return project_root() / "extension"


def browsers() -> dict[str, Path]:
    return BROWSERS_MAC if sys.platform == "darwin" else BROWSERS_LINUX


def extension_id(manifest_path: Path | None = None) -> str:
    """Compute Chrome's extension ID from the public key in the manifest.

    Chrome takes SHA-256 of the DER public key, keeps the first 16 bytes,
    and maps each hex nibble 0-f onto the letters a-p.
    """
    manifest_path = manifest_path or (extension_dir() / "manifest.json")
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    key_b64 = manifest.get("key")
    if not key_b64:
        raise RuntimeError(
            f"{manifest_path} has no 'key' field — run scripts/genkey.py to create one"
        )
    digest = hashlib.sha256(base64.b64decode(key_b64)).hexdigest()[:32]
    return "".join(chr(ord("a") + int(ch, 16)) for ch in digest)


def _write_executable(path: Path, contents: str) -> None:
    path.parent.mkdir(mode=0o700, parents=True, exist_ok=True)
    path.write_text(contents, encoding="utf-8")
    path.chmod(path.stat().st_mode | stat.S_IXUSR | stat.S_IRUSR | stat.S_IWUSR)


def write_launchers() -> tuple[Path, Path]:
    """Create ~/.tvault/bin/tvault and ~/.tvault/bin/tvault-host."""
    ensure_home()
    bindir = home() / "bin"
    python = Path(sys.executable).resolve()
    root = project_root()

    host = bindir / "tvault-host"
    _write_executable(
        host,
        "#!/bin/sh\n"
        "# Generated by 'tvault install-chrome'. Launched by Chrome, not by you.\n"
        f'PYTHONPATH="{root}" exec "{python}" -m tvault.nativehost "$@"\n',
    )

    cli = bindir / "tvault"
    _write_executable(
        cli,
        "#!/bin/sh\n"
        "# Generated by 'tvault install-chrome'.\n"
        f'PYTHONPATH="{root}" exec "{python}" -m tvault "$@"\n',
    )
    return cli, host


def host_manifest(host_path: Path, ext_id: str) -> dict:
    return {
        "name": HOST_NAME,
        "description": "tvault — local TOTP and password vault",
        "path": str(host_path),
        "type": "stdio",
        "allowed_origins": [f"chrome-extension://{ext_id}/"],
    }


def install_chrome(args) -> int:
    ext_id = extension_id()
    cli, host = write_launchers()
    manifest = host_manifest(host, ext_id)

    wanted = args.browser or list(browsers().keys())
    installed: list[tuple[str, Path]] = []
    skipped: list[str] = []

    for name in wanted:
        base = browsers().get(name)
        if base is None:
            ui.warn(f"unknown browser {name!r}")
            continue
        if not base.exists():
            skipped.append(name)
            continue
        target_dir = base / "NativeMessagingHosts"
        target_dir.mkdir(parents=True, exist_ok=True)
        target = target_dir / f"{HOST_NAME}.json"
        target.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
        os.chmod(target, 0o600)
        installed.append((name, target))

    if not installed:
        ui.err("no supported browser profile found")
        ui.info(f"looked in: {', '.join(str(b) for b in browsers().values())}")
        return 1

    for name, target in installed:
        ui.ok(f"native host installed for {ui.BOLD}{name}{ui.RESET}")
        print(f"  {ui.GREY}{target}{ui.RESET}")
    if skipped:
        ui.info(f"not installed (browser not found): {', '.join(skipped)}")

    print()
    print(f"{ui.BOLD}Load the extension{ui.RESET}")
    print(f"  1. Open {ui.CYAN}chrome://extensions{ui.RESET}")
    print("  2. Turn on Developer mode (top right)")
    print("  3. Click 'Load unpacked' and choose:")
    print(f"     {ui.BOLD}{extension_dir()}{ui.RESET}")
    print(f"  4. Confirm the ID reads {ui.BOLD}{ext_id}{ui.RESET}")
    print()
    print(f"{ui.BOLD}Optional — put the CLI on your PATH{ui.RESET}")
    print(f"  echo 'export PATH=\"{home()}/bin:$PATH\"' >> ~/.zshrc && exec zsh")
    return 0


def uninstall_chrome(args) -> int:
    removed = []
    for name, base in browsers().items():
        target = base / "NativeMessagingHosts" / f"{HOST_NAME}.json"
        if target.exists():
            target.unlink()
            removed.append(name)
    if removed:
        ui.ok(f"removed native host for: {', '.join(removed)}")
    else:
        ui.info("nothing to remove")
    return 0
